- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: 192.168.101.84
  become: yes
  tasks:
    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest